apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
spec:
  type: LoadBalancer  # Use NodePort if you're running Kubernetes locally
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pgadmin
