# PostgreSQL Deployment
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: django
spec:
  ports:
    - port: 5432
  selector:
    app: django
    tier: postgres

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: django
    tier: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
      containers:
        - image: postgres:latest
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: "django_api"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "1234"



              